services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=discord
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=hydra
      - ADMINER_DEFAULT_SERVER=mariadb

  discord_bot:
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    build: .
    restart: unless-stopped
    env_file: ".env"